"use client"

import { useState } from "react"
import { ChevronDown, ChevronUp, ChevronsUpDown, Trash2 } from "lucide-react"

import {
  FIELD_TYPE_OPTIONS,
  OPTIONS_FIELD_TYPES,
  createEmptyField,
  isAutoGeneratedKey,
  isValidKey,
  slugify,
  type ComplementaryActivationMode,
  type DynamicFormField,
} from "@/lib/schema-model"
import { usePages } from "@/hooks/use-pages"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { LabelWithHint } from "@/components/label-with-hint"
import { Textarea } from "@/components/ui/textarea"
import { Switch } from "@/components/ui/switch"
import { Badge } from "@/components/ui/badge"
import { ComboboxInput } from "@/components/combobox-input"
import { TagListEditor } from "@/components/tag-list-editor"
import { OptionalBlock } from "@/components/optional-block"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible"

const ACTIVATION_MODE_OPTIONS: { value: ComplementaryActivationMode; label: string }[] = [
  { value: "truthy", label: "Sempre que a pergunta principal tiver resposta" },
  { value: "always", label: "Sempre mostrar" },
  { value: "never", label: "Nunca mostrar (mantido como referência)" },
  { value: "equals_any", label: "Só quando a resposta bater com valores específicos" },
]

interface FieldEditorProps {
  field: DynamicFormField
  onChange: (field: DynamicFormField) => void
  onRemove: () => void
  onMoveUp?: () => void
  onMoveDown?: () => void
  allowComplementary?: boolean
  /** Only show key-format errors after the admin has attempted to save. */
  showErrors?: boolean
}

export function FieldEditor({
  field,
  onChange,
  onRemove,
  onMoveUp,
  onMoveDown,
  allowComplementary = true,
  showErrors = false,
}: FieldEditorProps) {
  const [open, setOpen] = useState(field.field_title.trim().length === 0)
  const { data: pages } = usePages()

  function patch(partial: Partial<DynamicFormField>) {
    onChange({ ...field, ...partial })
  }

  function handleTitleChange(title: string) {
    const shouldSyncKey = isAutoGeneratedKey(field.field_key, "field") || field.field_key.trim().length === 0
    patch({
      field_title: title,
      field_key: shouldSyncKey ? slugify(title) || field.field_key : field.field_key,
    })
  }

  const showOptions = OPTIONS_FIELD_TYPES.includes(field.field_type)
  const showMaxLength = field.field_type === "text" || field.field_type === "formatted_text"
  const showDateStrategy = field.field_type === "date"
  const showStorageFormat = field.field_type === "formatted_text"

  const pageOptions = (pages ?? []).map((p) => p.page_key)
  const activationMode = field.metadata?.complementary_activation_mode ?? "truthy"
  const activationValues = (field.complementary_field?.metadata?.complementary_active_when_values ??
    field.metadata?.complementary_active_when_values ??
    []) as unknown[]

  return (
    <div className="rounded-md border bg-card">
      <Collapsible open={open} onOpenChange={setOpen}>
        <div className="flex items-center gap-2 p-2.5">
          <div className="flex flex-col">
            <button
              type="button"
              onClick={onMoveUp}
              disabled={!onMoveUp}
              className="text-muted-foreground hover:text-foreground disabled:opacity-20"
            >
              <ChevronUp className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              onClick={onMoveDown}
              disabled={!onMoveDown}
              className="text-muted-foreground hover:text-foreground disabled:opacity-20"
            >
              <ChevronDown className="h-3.5 w-3.5" />
            </button>
          </div>

          <CollapsibleTrigger asChild>
            <button type="button" className="flex flex-1 items-center gap-2 text-left">
              <span className="text-sm font-medium">
                {field.field_title.trim() || "Pergunta sem título"}
              </span>
              <Badge variant="outline" className="text-[10px]">
                {FIELD_TYPE_OPTIONS.find((o) => o.value === field.field_type)?.label}
              </Badge>
              {field.is_field_mandatory && (
                <Badge variant="outline" className="text-[10px]">
                  obrigatória
                </Badge>
              )}
              <ChevronsUpDown className="ml-auto h-3.5 w-3.5 text-muted-foreground" />
            </button>
          </CollapsibleTrigger>

          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="h-7 w-7 text-destructive hover:text-destructive"
            onClick={onRemove}
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>

        <CollapsibleContent>
          <div className="space-y-4 border-t p-3">
            <div className="grid grid-cols-2 gap-3">
              <div className="col-span-2 space-y-1.5">
                <Label>Pergunta</Label>
                <Input
                  value={field.field_title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="ex: Sobre o que você sonhou?"
                />
              </div>

              <div className="space-y-1.5">
                <Label>Chave do campo</Label>
                <Input
                  value={field.field_key}
                  onChange={(e) => patch({ field_key: e.target.value })}
                  className="font-mono text-xs"
                />
                {showErrors && !isValidKey(field.field_key) ? (
                  <p className="text-[11px] text-destructive">
                    Deve estar em snake_case (ex: principal_insight)
                  </p>
                ) : (
                  <p className="text-[11px] text-muted-foreground">
                    Mantenha estável entre versões — mudar isso desconecta respostas antigas.
                  </p>
                )}
              </div>

              <div className="space-y-1.5">
                <Label>Tipo de resposta</Label>
                <Select
                  value={field.field_type}
                  onValueChange={(v) =>
                    patch({ field_type: v as DynamicFormField["field_type"] })
                  }
                >
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {FIELD_TYPE_OPTIONS.map((o) => (
                      <SelectItem key={o.value} value={o.value}>
                        {o.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="col-span-2 space-y-1.5">
                <Label>Texto de apoio</Label>
                <Textarea
                  rows={2}
                  value={field.field_description ?? ""}
                  onChange={(e) => patch({ field_description: e.target.value })}
                  placeholder="Texto opcional mostrado abaixo da pergunta"
                />
              </div>
            </div>

            {showOptions && (
              <div className="space-y-1.5">
                <Label>Opções</Label>
                <TagListEditor
                  values={field.options}
                  onChange={(options) => patch({ options })}
                  placeholder="Digite uma opção e pressione Enter"
                />
                <div className="flex items-center justify-between pt-1">
                  <Label htmlFor={`${field.field_key}-multi`}>Permitir selecionar mais de uma</Label>
                  <Switch
                    id={`${field.field_key}-multi`}
                    checked={field.allows_multiple_selection}
                    onCheckedChange={(v) => patch({ allows_multiple_selection: v })}
                  />
                </div>
              </div>
            )}

            {showMaxLength && (
              <div className="space-y-1.5">
                <Label>Limite de caracteres (opcional)</Label>
                <Input
                  type="number"
                  min={1}
                  value={field.max_length ?? ""}
                  onChange={(e) =>
                    patch({
                      max_length: e.target.value === "" ? null : Number(e.target.value),
                    })
                  }
                  className="w-32"
                />
              </div>
            )}

            {showDateStrategy && (
              <div className="flex items-center justify-between">
                <Label htmlFor={`${field.field_key}-today`}>Preencher com a data de hoje</Label>
                <Switch
                  id={`${field.field_key}-today`}
                  checked={field.initial_date_strategy === "today"}
                  onCheckedChange={(v) => patch({ initial_date_strategy: v ? "today" : null })}
                />
              </div>
            )}

            {showStorageFormat && (
              <p className="text-xs text-muted-foreground">
                Armazenado como markdown — o app mobile aplica a formatação (negrito, listas, etc).
              </p>
            )}

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <LabelWithHint hint="Controla onde essa resposta aparece fora do formulário. 'Título da entrada' e 'Resumo da entrada' definem o que é mostrado na lista do diário do usuário — normalmente só uma pergunta de cada tipo por formulário.">
                  Usado como
                </LabelWithHint>
                <Select
                  value={field.summary_role ?? "none"}
                  onValueChange={(v) =>
                    patch({
                      summary_role: v === "none" ? null : (v as "title" | "description"),
                    })
                  }
                >
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">Pergunta comum</SelectItem>
                    <SelectItem value="title">Título da entrada (aparece na lista do diário)</SelectItem>
                    <SelectItem value="description">Resumo da entrada</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-3 pt-1">
                <div className="flex items-center justify-between">
                  <Label htmlFor={`${field.field_key}-mandatory`}>Obrigatória</Label>
                  <Switch
                    id={`${field.field_key}-mandatory`}
                    checked={field.is_field_mandatory}
                    onCheckedChange={(v) => patch({ is_field_mandatory: v })}
                  />
                </div>
                <div className="flex items-center justify-between">
                  <LabelWithHint
                    htmlFor={`${field.field_key}-readonly`}
                    hint="O usuário vê essa pergunta no formulário, mas não consegue editá-la — usado para mostrar um valor fixo ou preenchido automaticamente."
                  >
                    Somente leitura
                  </LabelWithHint>
                  <Switch
                    id={`${field.field_key}-readonly`}
                    checked={field.is_read_only}
                    onCheckedChange={(v) => patch({ is_read_only: v })}
                  />
                </div>
                <div className="flex items-center justify-between">
                  <LabelWithHint
                    htmlFor={`${field.field_key}-pai`}
                    hint="Marca essa resposta como material para o Plano de Ação de Integração (PAI) — o resumo que o usuário monta depois de registrar a Experiência. Use em perguntas como 'principal insight' ou 'próximo passo'."
                  >
                    Alimenta o Plano de Ação (PAI)
                  </LabelWithHint>
                  <Switch
                    id={`${field.field_key}-pai`}
                    checked={field.is_pai_eligible}
                    onCheckedChange={(v) => patch({ is_pai_eligible: v })}
                  />
                </div>
              </div>
            </div>

            <OptionalBlock
              label="Dica (tooltip)"
              hint="Um texto de ajuda que aparece quando o usuário toca num ícone de informação ao lado da pergunta, no app."
              enabled={!!field.field_tooltip}
              onToggle={(enabled) =>
                patch({ field_tooltip: enabled ? { title: "", description: "" } : null })
              }
            >
              <div className="space-y-2">
                <Input
                  placeholder="Título da dica (opcional)"
                  value={field.field_tooltip?.title ?? ""}
                  onChange={(e) =>
                    patch({
                      field_tooltip: {
                        description: field.field_tooltip?.description ?? "",
                        title: e.target.value,
                      },
                    })
                  }
                />
                <Textarea
                  rows={2}
                  placeholder="Texto da dica"
                  value={field.field_tooltip?.description ?? ""}
                  onChange={(e) =>
                    patch({
                      field_tooltip: {
                        title: field.field_tooltip?.title,
                        description: e.target.value,
                      },
                    })
                  }
                />
              </div>
            </OptionalBlock>

            <OptionalBlock
              label="Link para uma página de conteúdo"
              hint="Adiciona um link clicável junto da pergunta, apontando para uma Página cadastrada em Páginas (ex: Termos de Uso)."
              enabled={!!field.link}
              onToggle={(enabled) =>
                patch({
                  link: enabled ? { label: "", destination_key: "", page_key: "" } : null,
                })
              }
            >
              <div className="space-y-2">
                <Input
                  placeholder="Texto do link (ex: Termos de Uso)"
                  value={field.link?.label ?? ""}
                  onChange={(e) =>
                    patch({
                      link: {
                        label: e.target.value,
                        destination_key: field.link?.destination_key ?? "",
                        page_key: field.link?.page_key ?? "",
                      },
                    })
                  }
                />
                <div className="grid grid-cols-2 gap-2">
                  <div className="space-y-1">
                    <Input
                      placeholder="Chave de destino"
                      value={field.link?.destination_key ?? ""}
                      onChange={(e) =>
                        patch({
                          link: {
                            label: field.link?.label ?? "",
                            destination_key: e.target.value,
                            page_key: field.link?.page_key ?? "",
                          },
                        })
                      }
                      className="font-mono text-xs"
                    />
                    {showErrors && field.link && !isValidKey(field.link.destination_key) && (
                      <p className="text-[11px] text-destructive">Deve estar em snake_case</p>
                    )}
                  </div>
                  <div className="space-y-1">
                    <ComboboxInput
                      value={field.link?.page_key ?? ""}
                      onChange={(v) =>
                        patch({
                          link: {
                            label: field.link?.label ?? "",
                            destination_key: field.link?.destination_key ?? "",
                            page_key: v,
                          },
                        })
                      }
                      options={pageOptions}
                      placeholder="Chave da página"
                      className="font-mono text-xs"
                    />
                    {showErrors && field.link?.page_key && !isValidKey(field.link.page_key) && (
                      <p className="text-[11px] text-destructive">Deve estar em snake_case</p>
                    )}
                  </div>
                </div>
              </div>
            </OptionalBlock>

            {allowComplementary && (
              <OptionalBlock
                label="Pergunta de acompanhamento"
                hint="Uma pergunta extra que só aparece dependendo da resposta desta — útil para pedir mais detalhes quando fizer sentido."
                enabled={!!field.complementary_field}
                onToggle={(enabled) =>
                  patch({
                    complementary_field: enabled ? createEmptyField() : null,
                    metadata: enabled
                      ? { ...field.metadata, complementary_activation_mode: "truthy" }
                      : field.metadata,
                  })
                }
              >
                <div className="space-y-3">
                  <div className="space-y-1.5">
                    <Label>Mostrar quando…</Label>
                    <Select
                      value={activationMode}
                      onValueChange={(v) =>
                        patch({
                          metadata: {
                            ...field.metadata,
                            complementary_activation_mode: v as ComplementaryActivationMode,
                          },
                        })
                      }
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {ACTIVATION_MODE_OPTIONS.map((o) => (
                          <SelectItem key={o.value} value={o.value}>
                            {o.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  {activationMode === "equals_any" && (
                    <div className="space-y-1.5">
                      <Label>Valores que ativam a pergunta</Label>
                      <TagListEditor
                        values={activationValues.map((v) => String(v))}
                        onChange={(values) =>
                          patch({
                            metadata: {
                              ...field.metadata,
                              complementary_active_when_values: values,
                            },
                          })
                        }
                      />
                    </div>
                  )}

                  {field.complementary_field && (
                    <FieldEditor
                      field={field.complementary_field}
                      onChange={(complementary_field) => patch({ complementary_field })}
                      onRemove={() => patch({ complementary_field: null })}
                      allowComplementary={false}
                      showErrors={showErrors}
                    />
                  )}
                </div>
              </OptionalBlock>
            )}
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>
  )
}
