"use client"

import { useState } from "react"
import { ChevronDown, ChevronUp, ChevronsUpDown, Plus, Trash2 } from "lucide-react"

import {
  createEmptyField,
  isAutoGeneratedKey,
  isValidKey,
  slugify,
  SECTION_INFO_BOX_ICON_OPTIONS,
  type DynamicFormSection,
} from "@/lib/schema-model"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { LabelWithHint } from "@/components/label-with-hint"
import { Textarea } from "@/components/ui/textarea"
import { Switch } from "@/components/ui/switch"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible"
import { OptionalBlock } from "@/components/optional-block"
import { FieldEditor } from "./field-editor"

interface SectionEditorProps {
  section: DynamicFormSection
  onChange: (section: DynamicFormSection) => void
  onRemove: () => void
  onMoveUp?: () => void
  onMoveDown?: () => void
  /** Only show key-format errors after the admin has attempted to save. */
  showErrors?: boolean
}

export function SectionEditor({
  section,
  onChange,
  onRemove,
  onMoveUp,
  onMoveDown,
  showErrors = false,
}: SectionEditorProps) {
  const [open, setOpen] = useState(true)

  function patch(partial: Partial<DynamicFormSection>) {
    onChange({ ...section, ...partial })
  }

  function handleTitleChange(title: string) {
    const shouldSyncKey =
      isAutoGeneratedKey(section.section_key, "section") || section.section_key.trim().length === 0
    patch({
      section_title: title,
      section_key: shouldSyncKey ? slugify(title) || section.section_key : section.section_key,
    })
  }

  function updateField(index: number, field: DynamicFormSection["fields"][number]) {
    const fields = [...section.fields]
    fields[index] = field
    patch({ fields })
  }

  function removeField(index: number) {
    patch({ fields: section.fields.filter((_, i) => i !== index) })
  }

  function moveField(index: number, direction: -1 | 1) {
    const target = index + direction
    if (target < 0 || target >= section.fields.length) return
    const fields = [...section.fields]
    ;[fields[index], fields[target]] = [fields[target], fields[index]]
    patch({ fields })
  }

  function addField() {
    patch({ fields: [...section.fields, createEmptyField()] })
  }

  return (
    <div className="rounded-lg border bg-muted/20">
      <Collapsible open={open} onOpenChange={setOpen}>
        <div className="flex items-center gap-2 p-3">
          <div className="flex flex-col">
            <button
              type="button"
              onClick={onMoveUp}
              disabled={!onMoveUp}
              className="text-muted-foreground hover:text-foreground disabled:opacity-20"
            >
              <ChevronUp className="h-4 w-4" />
            </button>
            <button
              type="button"
              onClick={onMoveDown}
              disabled={!onMoveDown}
              className="text-muted-foreground hover:text-foreground disabled:opacity-20"
            >
              <ChevronDown className="h-4 w-4" />
            </button>
          </div>

          <CollapsibleTrigger asChild>
            <button type="button" className="flex flex-1 items-center gap-2 text-left">
              <span className="font-medium">
                {section.section_title.trim() || "Seção sem título"}
              </span>
              <span className="text-xs text-muted-foreground">
                {section.fields.length}{" "}
                {section.fields.length === 1 ? "pergunta" : "perguntas"}
              </span>
              <ChevronsUpDown className="ml-auto h-4 w-4 text-muted-foreground" />
            </button>
          </CollapsibleTrigger>

          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="h-7 w-7 text-destructive hover:text-destructive"
            onClick={onRemove}
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>

        <CollapsibleContent>
          <div className="space-y-4 border-t p-3">
            <div className="grid grid-cols-2 gap-3">
              <div className="col-span-2 space-y-1.5">
                <Label>Título da seção</Label>
                <Input
                  value={section.section_title}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="ex: Narrativa"
                />
              </div>
              <div className="space-y-1.5">
                <LabelWithHint hint="Identifica essa seção internamente — é preenchida sozinha a partir do título, então normalmente você não precisa mexer aqui. Ela é o que liga essa seção às respostas já dadas pelos usuários: se você mudar a chave de uma versão já publicada, as respostas antigas dessa seção deixam de aparecer ligadas a ela. Pode renomear o título à vontade — só evite editar a chave depois de publicar.">
                  Chave da seção
                </LabelWithHint>
                <Input
                  value={section.section_key}
                  onChange={(e) => patch({ section_key: e.target.value })}
                  className="font-mono text-xs"
                />
                {showErrors && !isValidKey(section.section_key) && (
                  <p className="text-[11px] text-destructive">
                    Deve estar em snake_case (ex: narrativa)
                  </p>
                )}
              </div>
              <div className="flex items-end justify-between pb-1.5">
                <LabelWithHint
                  htmlFor={`${section.section_key}-expanded`}
                  hint="Quando ligado, essa seção já aparece aberta pro usuário ao entrar no formulário, sem precisar tocar pra expandir."
                >
                  Iniciar expandida
                </LabelWithHint>
                <Switch
                  id={`${section.section_key}-expanded`}
                  checked={section.is_initially_expanded}
                  onCheckedChange={(v) => patch({ is_initially_expanded: v })}
                />
              </div>
              <div className="col-span-2 space-y-1.5">
                <Label>Descrição da seção</Label>
                <Textarea
                  rows={2}
                  value={section.section_description ?? ""}
                  onChange={(e) => patch({ section_description: e.target.value })}
                  placeholder="Texto de apoio opcional, mostrado abaixo do título da seção"
                />
              </div>
            </div>

            <OptionalBlock
              label="Caixa de informação"
              hint="Um bloco de destaque com ícone, título e texto, mostrado no topo da seção — útil pra dar contexto antes das perguntas."
              enabled={!!section.section_info_box}
              onToggle={(enabled) =>
                patch({
                  section_info_box: enabled
                    ? { icon: "lightbulb", title: "", description: "" }
                    : null,
                })
              }
            >
              <div className="space-y-2">
                <div className="grid grid-cols-2 gap-2">
                  <Select
                    value={section.section_info_box?.icon ?? "lightbulb"}
                    onValueChange={(icon) =>
                      patch({
                        section_info_box: {
                          icon,
                          title: section.section_info_box?.title ?? "",
                          description: section.section_info_box?.description ?? "",
                        },
                      })
                    }
                  >
                    <SelectTrigger className="w-full">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {SECTION_INFO_BOX_ICON_OPTIONS.map((o) => (
                        <SelectItem key={o.value} value={o.value}>
                          {o.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Input
                    placeholder="Título"
                    value={section.section_info_box?.title ?? ""}
                    onChange={(e) =>
                      patch({
                        section_info_box: {
                          icon: section.section_info_box?.icon,
                          title: e.target.value,
                          description: section.section_info_box?.description ?? "",
                        },
                      })
                    }
                  />
                </div>
                <Textarea
                  rows={2}
                  placeholder="Texto de apoio mostrado na caixa de informação"
                  value={section.section_info_box?.description ?? ""}
                  onChange={(e) =>
                    patch({
                      section_info_box: {
                        icon: section.section_info_box?.icon,
                        title: section.section_info_box?.title ?? "",
                        description: e.target.value,
                      },
                    })
                  }
                />
              </div>
            </OptionalBlock>

            <div className="space-y-2">
              <Label className="text-xs text-muted-foreground">Perguntas</Label>
              {section.fields.map((field, index) => (
                // Keyed by index, not field_key: field_key is auto-slugified
                // from the title on every keystroke for new fields, which
                // would remount the input (and drop focus) on every letter.
                <FieldEditor
                  key={index}
                  field={field}
                  onChange={(f) => updateField(index, f)}
                  onRemove={() => removeField(index)}
                  onMoveUp={index > 0 ? () => moveField(index, -1) : undefined}
                  onMoveDown={
                    index < section.fields.length - 1 ? () => moveField(index, 1) : undefined
                  }
                  showErrors={showErrors}
                />
              ))}
              <Button type="button" variant="outline" size="sm" onClick={addField}>
                <Plus className="mr-1.5 h-3.5 w-3.5" />
                Adicionar pergunta
              </Button>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>
  )
}
