export type DynamicFormFieldType =
  | "text"
  | "formatted_text"
  | "date"
  | "selection"
  | "dropdown"
  | "boolean"
  | "checkbox"

export const FIELD_TYPE_OPTIONS: { value: DynamicFormFieldType; label: string }[] = [
  { value: "text", label: "Texto" },
  { value: "formatted_text", label: "Texto formatado (markdown)" },
  { value: "date", label: "Data" },
  { value: "selection", label: "Seleção" },
  { value: "dropdown", label: "Lista suspensa" },
  { value: "boolean", label: "Sim / Não" },
  { value: "checkbox", label: "Caixa de seleção" },
]

export const OPTIONS_FIELD_TYPES: DynamicFormFieldType[] = ["selection", "dropdown", "checkbox"]

/** Chave fixa do formulário de PAI (Plano de Ação de Integração) — só existe um. */
export const PAI_PLAN_SCHEMA_KEY = "pai_plan"

/**
 * Chaves de ícone confirmadas pelo dev mobile para section_info_box.icon —
 * o Flutter também aceita light_bulb/idea como aliases legados de lightbulb,
 * mas não oferecemos esses aliases aqui (ver gaia-backend/docs/pending-questions.md).
 */
export const SECTION_INFO_BOX_ICON_OPTIONS = [
  { value: "lightbulb", label: "Lâmpada" },
  { value: "info", label: "Informação" },
  { value: "sparkles", label: "Brilho" },
] as const

export type ComplementaryActivationMode = "always" | "never" | "truthy" | "equals_any"

export interface DynamicFormFieldTooltip {
  title?: string
  description: string
}

export interface DynamicFormFieldLink {
  label: string
  destination_key: string
  page_key: string
}

export interface DynamicFormSectionInfoBox {
  icon?: string
  title: string
  description: string
}

export interface DynamicFormFieldMetadata {
  complementary_activation_mode?: ComplementaryActivationMode
  complementary_active_when_values?: unknown[]
  [key: string]: unknown
}

export interface DynamicFormField {
  field_key: string
  field_title: string
  field_description?: string
  field_type: DynamicFormFieldType
  is_field_mandatory: boolean
  is_pai_eligible: boolean
  options: string[]
  allows_multiple_selection: boolean
  is_read_only: boolean
  max_length?: number | null
  summary_role?: "title" | "description" | null
  initial_date_strategy?: "today" | null
  storage_format?: "markdown" | null
  field_tooltip?: DynamicFormFieldTooltip | null
  link?: DynamicFormFieldLink | null
  complementary_field?: DynamicFormField | null
  metadata?: DynamicFormFieldMetadata | null
}

export interface DynamicFormSection {
  section_key: string
  section_title: string
  section_description?: string
  is_initially_expanded: boolean
  fields: DynamicFormField[]
  section_info_box?: DynamicFormSectionInfoBox | null
}

let idCounter = 0

function uid(prefix: string): string {
  idCounter += 1
  return `${prefix}_${Date.now().toString(36)}_${idCounter.toString(36)}`
}

/** Shared with schema_key/page_key validation elsewhere in the admin — keep in sync. */
export const SNAKE_CASE_KEY_PATTERN = /^[a-z][a-z0-9]*(_[a-z0-9]+)*$/

export function isValidKey(value: string): boolean {
  return SNAKE_CASE_KEY_PATTERN.test(value)
}

export function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
}

export function createEmptyField(): DynamicFormField {
  return {
    field_key: uid("field"),
    field_title: "",
    field_description: "",
    field_type: "text",
    is_field_mandatory: false,
    is_pai_eligible: false,
    options: [],
    allows_multiple_selection: false,
    is_read_only: false,
    max_length: null,
    summary_role: null,
    initial_date_strategy: null,
    storage_format: null,
    field_tooltip: null,
    link: null,
    complementary_field: null,
    metadata: null,
  }
}

export function createEmptySection(): DynamicFormSection {
  return {
    section_key: uid("section"),
    section_title: "",
    section_description: "",
    is_initially_expanded: true,
    fields: [],
    section_info_box: null,
  }
}

/** True when a key still looks machine-generated (never renamed by the admin). */
export function isAutoGeneratedKey(key: string, prefix: string): boolean {
  return new RegExp(`^${prefix}_[0-9a-z]+_[0-9a-z]+$`).test(key)
}

export function toDynamicFormSections(raw: unknown): DynamicFormSection[] {
  if (!Array.isArray(raw)) return []
  return raw as DynamicFormSection[]
}

/** Recursively collects every invalid section_key/field_key/link key in a set of sections. */
export function collectInvalidKeys(sections: DynamicFormSection[]): string[] {
  const invalid: string[] = []

  function checkKey(key: string) {
    if (!isValidKey(key)) invalid.push(key)
  }

  function checkField(field: DynamicFormField) {
    checkKey(field.field_key)
    if (field.link) {
      checkKey(field.link.destination_key)
      if (field.link.page_key) checkKey(field.link.page_key)
    }
    if (field.complementary_field) checkField(field.complementary_field)
  }

  for (const section of sections) {
    checkKey(section.section_key)
    for (const field of section.fields) checkField(field)
  }

  return invalid
}
